version: '3.8'
services:
  personal-homepage-nx-db:
    restart: always
    image: postgres:13
    container_name: personal-homepage-nx-db-dev
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5750:5432
    expose:
      - 5750

  personal-homepage-nx-pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: personal-homepage-pgadmin4-nx
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '8750:80'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - personal-homepage-nx-db

volumes:
  db-data:
  pgadmin-data:
    driver: local
