import { Inter } from '@next/font/google';

import './global.css';

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  // weight: ['400', '700', '900'],
});

export const metadata = {
  title: 'Welcome to next',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <body className="bg-gray-100 text-gray-900 dark:bg-gray-900 dark:text-gray-100">{children}</body>
    </html>
  );
}
